### ISSUE TITLE
Rosmake Error

### ISSUE THREAD

**Issue by hakanbaysal** [Ronan0912/ros_opentld#10]
Hi

I have a problem about rosmake. It is below.

[rosmake-0] Finished <<< opentld [PASS] [ 0.07 seconds ]  
[rosmake-2] Finished <<< tld_msgs [PASS] [ 0.65 seconds ]  
[rosmake-2] Starting >>> tld_tracker [ make ]  
[rosmake-2] Finished <<< tld_tracker [PASS] [ 0.52 seconds ]   

What can I do for it ? 
Thank you for answer.

**Comment by Ronan0912** [comment]
Hello,

ros_opentld is catkinized and must be built in a catkin workspace (with catkin_make and not with rosmake).

Ronan

**Comment by hakanbaysal** [comment]
But I used on Ros Fuerte and its worked. I want to use its again.

**Comment by Ronan0912** [comment]
OK! You can switch back from one revision.
