### ISSUE TITLE
The GUI node doesn't start tracking after hitting Enter

### ISSUE THREAD

**Issue by dbs0412247** [Ronan0912/ros_opentld#12]
Hi Ronan, as the title suggests, the GUI node (started by roslaunch tld_tracker ros_tld_gui.launch) doesn't seem to respond to the Enter key being pressed after having a bounding box selected. 

Steps I've taken up to now: 
1) git clone'd your repo
2) catkin_make 
3) editted ros_tld_gui.launch to provide the correct image topic
4) roslaunch'd my camera node and the TLD gui node
5) tried F5 refreshing on the GUI node, that works
6) clicked and dragged on the GUI to create a bounding box, that worked too
7) pressed Enter with a bounding box on screen, but this doesn't work!
On the command line, "Enter" and "Press X :  108  Y :  160.5" and "Release X :  233  Y :  258.5"
can be seen when Enter is pressed and the mouse is clicked and dragged， but tracking just doesn't happen. What do?

Any help would be greatly appreciated.

**Comment by Ronan0912** [comment]
Hi Adrian,

Have you launched and configured the tld_tracker_node? The GUI node is only a way to monitor the tracker.

Ronan

**Comment by dbs0412247** [comment]
Yes it worked, and that makes me an idiot who didn't read through the README clearly. 

Thanks a bunch Ronan.

**Comment by lhsdch** [comment]
Hi, I am a fresher in ROS, and I don't know how to launch and configure tld_tracker_node, Could you please tell me?
