### ISSUE TITLE
ROS_opentld:launch and configure ros_tld_gui.launch 

### ISSUE THREAD

**Issue by lhsdch** [Ronan0912/ros_opentld#16]
Hello,
      My name is Liu Hao from China, I'm learning ROS_opentld recently, and there are many questions not clear in launching and configuring  ros_tld_gui.launch. I use the standard usb_cam package from Indigo for video, but it doesn't work. Could you sent me a complete tutorial that I can run this code sucessfully?

**Comment by Ronan0912** [comment]
Hi Liu,

The README file contains everything to start.

If you are a beginner on the ROS environment, you can do the tutorials from the ROS website (http://wiki.ros.org//ROS/Tutorials).

Thanks,
