### ISSUE TITLE
How to install this package?

### ISSUE THREAD

**Issue by Imzlz** [Ronan0912/ros_opentld#3]
Hello,

It looks like what you have done is awesome and I try to use your package. Under Ubuntu 12.04, I command like this:
$ git clone https://github.com/Ronan0912/ros_opentld.git
$ roscd ros_opentld
$ rosmake
During the process of compile your package, it always shows problem. Could you help me ?

**Comment by Ronan0912** [comment]
Hi,

You can try to build directly tld_tracker instead of the ros_opentld stack :
$ roscd tld_tracker
$ rosmake

Can you give me more information about the problem if there is still one? (error in the console)

Ronan

**Comment by Imzlz** [comment]
Thank you!
Now it works, and as you said in the README, "In the two launch files, you can configure the input video stream"....I want to use this package to track something from the camera on the robot, so I try to modify the "image_topic" in the launch file, then I roslaunch the ros_tld_gui.launch, but there is no result.

**Comment by Imzlz** [comment]
If you could ,please let me know more about how to use this amazing package. Moreover, I try to read your code, so this package can been used without QT?(Because I haven't install QT)

**Comment by Ronan0912** [comment]
Qt is installed by default with the ROS distribution. Moreover, if Qt is not installed on your system, the build can't success.
In the two launch files (ros_tld_tracker.launch and ros_tld_gui.launch), you need to replace the default image_topic argument "im_acq" by your camera topic name (ex : /openni/rgb/image_rect_color if you are using the kinect). 

$ roslaunch tld_tracker ros_tld_tracker.launch
$ roslaunch tld_tracker ros_tld_gui.launch

Press f5 in the GUI to refresh the image for the bounding box selection.

Ronan

**Comment by Imzlz** [comment]
It seems that I need to refresh the image by myself, could I do that, draw the box(select the object) and the image will change by itself in real-time, int the same time tracking the object? (like this version, https://github.com/alantrrs/OpenTLD ).....I am the newer for ros and tld! Thank you for your help

**Comment by Ronan0912** [comment]
1 - Refresh the image in order to obtain a good point of view of your target.
2 - Select the target by drawing a bounding box.
3 - Press the Enter key.
4 - You will see the bounding box moving accordingly to the movements of your target.

Ronan

**Comment by Imzlz** [comment]
OK, I change the "im_acq" to be the correct topic and get the picture(it will stay for the first frame), then draw a bounding box, then hit the Enter, but the image still don't update......Moreover, I test it with the rosbag and I will try with the AR.drone tomorrow

**Comment by Ronan0912** [comment]
Did you change im_acq in the two launch files? Is there a message on the tracker_node console which says "Waiting for a BB"?

Can you verify that your video feed is ok? (rosrun image_view image_view image:=/your/topic/name)

Ronan

**Comment by Imzlz** [comment]
OK, I got it finally. I usually think that I only need to roslaunch one launch of two and I can realize tracking because they are launch not nodes. Base on your reply, I try to roslaunch both of them and it works!

Thank you for your help and your amazing work!

**Comment by shrijan00** [comment]
Hi,
So i can track the desired object but when i occlude it with some other object, the tracking thing is not robust as it loses tracking for a while.
