### ISSUE TITLE
Blank Picture in TLD GUI

### ISSUE THREAD

**Issue by zardchim** [Ronan0912/ros_opentld#4]
Hi Ronan,

```
Thank you for your contribution of the OpenTld! I am trying to use your code to track object with my Kinect, with the procedure listed below:
```
1. Change the default image_topic to the topic I want in both launch files
2. Test the rostopic image with rosrun image_view image_view image:=/camera/rgb/image_color   (and it's Okay)
3. roslaunch tld_tracker ros_tld_tracker.launch
4. roslaunch tld_tracker ros_tld_gui.launch

But I can't see anything in the TLD, it only shows up a white blank page, could you please teach me how to deal with this =] ? Thanks in advance!!

Best Regards,
Chim

**Comment by zardchim** [comment]
Oh the tld_gui show image accidentally, and I don't know the reason -,- Thank you anyway!

**Comment by jespestana** [comment]
Hey, if the tld_gui is correctly subscribed/connected to an existing image topic then you need to press F5 to refresh the image on the GUI. Sometimes the tld_gui will be initialized with a Blank Image, but pressing F5 after the camera is correctly initialized will put the latest image on the GUI. Then you should be able to select the target and proceed with you experiments.

Good luck!!

Jesus
