### ISSUE TITLE
Ros_OpenTLD getting B.box coordinate parameters ?

### ISSUE THREAD

**Issue by hakanbaysal** [Ronan0912/ros_opentld#6]
How to get coordinate of tracking object in bounding box as yml file ?

**Comment by Ronan0912** [comment]
The best way is to write a rosnode which subscribes to the bounding box topic and saves the coordinates in an yaml file.

**Comment by hakanbaysal** [comment]
thanks your answer
i have a problem; I can success with "opentld -p ../parameters.yml" parameter
but i want to run with "roslaunch tld_tracker ros_tld_tracker.launch -p ../parameters.yml"

**Comment by Ronan0912** [comment]
Sorry but the ROS wrapper does not include this functionality.

Date: Thu, 10 Apr 2014 04:58:04 -0700

**Comment by hakanbaysal** [comment]
What is the file name  in which you run OpenTLD ? 
We want to try to pass "-p ../parameters.yml" to OpenTLD.

**Comment by Ronan0912** [comment]
I don't run OpenTLD application. I only use the OpenTLD library and the UI has been reimplemented.

Ronan

Date: Thu, 10 Apr 2014 06:42:10 -0700
