### ISSUE TITLE
The box is still here when object moves out of sight

### ISSUE THREAD

**Issue by lanyusea** [Ronan0912/ros_opentld#8]
Hi, 

Thanks for building the ros package of opentld.

I just tested it but found the box is still here after I moving the object out of sight. The box keeps on the last position of the object until I move the object into its sight again.

I'm wondering is that just a problem on display or the position it returns is really kept on this position instead of returning nothing?

And what file should I modify if I want to change it behave as what I want (i.e. return nothing when object move out of sight)? I think I need to set a threshold on the recall value.

**Comment by Ronan0912** [comment]
Hi,

When the target wasn't found in the image (e.g. out of the field of view), the position isn't published and the GUI isn't informed (problem on display). I just made a commit to change that so now a fake bounding box (x = 1, y = 1, width = 1,  height = 1) is sent with a 0.0 confidence when the target can't be tracked (you can then filter the bounding box on the confidence value).

If you want, you can change this behavior in the "main.cpp" file (state tracking of the state machine) and in the "base_frame_graphics_view.cpp" file (function tracked_objet_changed).

I hope this will help you!

**Comment by lanyusea** [comment]
thanks so much.
