### ISSUE TITLE
Is it possible to rebuild this package in catkin workspace?

### ISSUE THREAD

**Issue by lanyusea** [Ronan0912/ros_opentld#9]
Hi, I'm trying to subscribe the BoundingBox topic and get the msg data in catkin but failed because catkin package cannot rely on the rosbuild package.

So I'm trying to rebuild the package in catkin workspace but I find it is really complicated for me to do this, especially there exist many CMakeLists.txt I do know how to handle also the original library (git-opentld) is here.

Can anyone give me some advice?  Which file should I put in src folder, which should I compile individually as share library and which should I withdraw?
I didn't realize I really do poorly in c language until this case :(

**Comment by Ronan0912** [comment]
Hi,

It should be possible to use a rosbuild package with catkin packages (even in Hydro) : http://wiki.ros.org/catkin/Tutorials/using_rosbuild_with_catkin

To "catkinize" a package you can follow these instructions : http://wiki.ros.org/catkin/migrating_from_rosbuild

I will try to migrate the packages to catkin in the next days (As you said, ros_opentld depends on the original library so the build process is a little more complicated...).

Ronan

**Comment by lanyusea** [comment]
Thanks Ronan, it is very kind of you.

You are right, I can use the msg defined in rosbuild package. It is my own problem and I solved it. Someone in rosAnswer told me it is the caused by the difference between rosbuild and catkin but actually it's not.

Thanks.

**Comment by Ronan0912** [comment]
FYI, I catkinized ros_opentld.

**Comment by lanyusea** [comment]
awesome
